restart -f
mem load -i {C:/Users/mohab/Desktop/Uni/Courses/Year 3 - 2nd term/Computer Arch/Project/Code/project/Test_Cases/MOHAB_TEST.mem} /main_processor/u0/U2/INSTRUCTION_CACHE
force -freeze sim:/main_processor/CLK 1 0, 0 {50 ps} -r 100
force -freeze sim:/main_processor/RST 1 0
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 0 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 0 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 0 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 0 ps  Iteration: 0  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 0 ps  Iteration: 0  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 0 ps  Iteration: 1  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 0 ps  Iteration: 1  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 50 ps  Iteration: 0  Instance: /main_processor/u0/U2
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 50 ps  Iteration: 0  Instance: /main_processor/u0/U2
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 50 ps  Iteration: 0  Instance: /main_processor/u0/U2
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 50 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 50 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 50 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 100 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 100 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 100 ps  Iteration: 0  Instance: /main_processor/u6/U1
force -freeze sim:/main_processor/RST 0 0
run
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 300 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 300 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 300 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 400 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 400 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 400 ps  Iteration: 0  Instance: /main_processor/u6/U1
force -freeze sim:/main_processor/IN_PORT 00000000000000000000000000000101 0
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 500 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 500 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 500 ps  Iteration: 0  Instance: /main_processor/u6/U1
force -freeze sim:/main_processor/IN_PORT 00000000000000000000000000010000 0
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 600 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 600 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 600 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 700 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 700 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 700 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 750 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 750 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 750 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 750 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 750 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 750 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 800 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 800 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 800 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 850 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 850 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 850 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 850 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 850 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 850 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 900 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 900 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 900 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 950 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 950 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 950 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1 ns  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1 ns  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1 ns  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1050 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1050 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1050 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1100 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1100 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1100 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1150 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1150 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1150 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 1150 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1150 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1150 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1200 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1200 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1200 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 1250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1250 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1300 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1300 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1300 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1350 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1400 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1400 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1400 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1400 ps  Iteration: 1  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1400 ps  Iteration: 1  Instance: /main_processor/u2/u1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1450 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1450 ps  Iteration: 1  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1450 ps  Iteration: 1  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1500 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1500 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1500 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 1550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1550 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1550 ps  Iteration: 1  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1550 ps  Iteration: 1  Instance: /main_processor/u2/u1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1600 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1600 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1600 ps  Iteration: 0  Instance: /main_processor/u6/U1
run
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD."=": metavalue detected, returning FALSE
#    Time: 1650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1650 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1700 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1700 ps  Iteration: 0  Instance: /main_processor/u6/U1
# ** Warning: NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0
#    Time: 1700 ps  Iteration: 0  Instance: /main_processor/u6/U1
